export const Colors = {
  light: {
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceVariant: '#F3F4F6',
    primary: '#22C55E',
    onPrimary: '#FFFFFF',
    primaryContainer: '#DCFCE7',
    secondary: '#3B82F6',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#DBEAFE',
    text: '#111827',
    textMuted: '#6B7280',
    border: '#E5E7EB',
    error: '#EF4444',
  },
  dark: {
    background: '#1a1c1a',
    surface: '#2f312f',
    surfaceVariant: '#45474c',
    primary: '#bcc7de',
    onPrimary: '#1e293b',
    primaryContainer: '#3c475a',
    secondary: '#b2c8ba',
    onSecondary: '#1a2d23',
    secondaryContainer: '#304d35',
    text: '#faf9f6',
    textMuted: '#dbdad7',
    border: '#75777d',
    error: '#ffdad6',
  }
};
